[discord]
[discord.mydiscord]

# You can get your token by following the instructions on
# https://github.com/42wim/matterbridge/wiki/Discord-bot-setup
# in particular that the "Members Intent" checkbox is important.
# If you want roles/groups mentions to be shown with names instead of ID, 
# you'll need to give your bot the "Manage Roles" permission.
Token="<DISCORD_TOKEN>"
Server="303217943234215948" # if you want to bridge https://discord.com/channels/8888888888888/7777777777777777, then this should be 8888888888888
AutoWebhooks=true
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "
# Map threads from other bridges on discord replies
PreserveThreading=false

[irc.myirc]
Nick="gb-bridge" # <== change this
NickServNick="gb-bridge" # <== change this if necessary (your nick registered with nickserv)
NickServPassword="<PASSOWRD>" # <== change this (your pass with nickserv)
Server="irc.libera.chat:6697"
UseTLS=true
UseSASL=true
SkipTLSVerify=false
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "

[[gateway]]
name="general-bridge"
enable=true

[[gateway.inout]]
account="irc.myirc"
channel="#gbdev"

[[gateway.inout]]
account="discord.mydiscord"
channel="general"

[[gateway]]
name="meta-bridge"
enable=true

[[gateway.inout]]
account="irc.myirc"
channel="#gbdev-meta"

[[gateway.inout]]
account="discord.mydiscord"
channel="meta"

[[gateway]]
name="ot-bridge"
enable=true

[[gateway.inout]]
account="irc.myirc"
channel="#gbdev-ot"

[[gateway.inout]]
account="discord.mydiscord"
channel="off-topic"

[[gateway]]
name="asm-bridge"
enable=true

[[gateway.inout]]
account="irc.myirc"
channel="#gbdev-asm"

[[gateway.inout]]
account="discord.mydiscord"
channel="asm-rgbds"

[[gateway]]
name="gfx-bridge"
enable=true

[[gateway.inout]]
account="irc.myirc"
channel="#gbdev-gfx"

[[gateway.inout]]
account="discord.mydiscord"
channel="graphics"

[[gateway]]
name="emudev-bridge"
enable=true

[[gateway.inout]]
account="irc.myirc"
channel="#gbdev-emudev"

[[gateway.inout]]
account="discord.mydiscord"
channel="emudev"

[[gateway]]
name="research-bridge"
enable=true

[[gateway.inout]]
account="irc.myirc"
channel="#gbdev-research"

[[gateway.inout]]
account="discord.mydiscord"
channel="research"

[[gateway]]
name="hw-bridge"
enable=true

[[gateway.inout]]
account="irc.myirc"
channel="#gbdev-hw"

[[gateway.inout]]
account="discord.mydiscord"
channel="hardware"
